from __future__ import annotations

from typing import Final


LABEL_DATE: Final[str] = "LABEL_DATE"
LABEL_TARGET_DATE_PREFIX: Final[str] = "LABEL_TARGET_DATE"

SERIES_SYMBOL: Final[str] = "SERIES_SYMBOL"
SERIES_SYMBOL_ID: Final[str] = "SERIES_SYMBOL_ID"
SERIES_ID: Final[str] = "SERIES_ID"
SERIES_ID_ID: Final[str] = "SERIES_ID_ID"

FEATURE_OPEN: Final[str] = "FEATURE_OPEN"
FEATURE_HIGH: Final[str] = "FEATURE_HIGH"
FEATURE_LOW: Final[str] = "FEATURE_LOW"
FEATURE_CLOSE: Final[str] = "FEATURE_CLOSE"
FEATURE_ADJ_CLOSE: Final[str] = "FEATURE_ADJ_CLOSE"
FEATURE_VOLUME: Final[str] = "FEATURE_VOLUME"
FEATURE_VALUE: Final[str] = "FEATURE_VALUE"

MARKET_PRICE_COLUMNS: Final[list[str]] = [
    SERIES_SYMBOL,
    LABEL_DATE,
    FEATURE_OPEN,
    FEATURE_HIGH,
    FEATURE_LOW,
    FEATURE_CLOSE,
    FEATURE_ADJ_CLOSE,
    FEATURE_VOLUME,
]
MARKET_PRICE_KEY: Final[list[str]] = [SERIES_SYMBOL, LABEL_DATE]
MARKET_PRICE_ID_KEY: Final[list[str]] = [SERIES_SYMBOL_ID, LABEL_DATE]
MARKET_PRICE_VALUE_COLUMNS: Final[list[str]] = MARKET_PRICE_COLUMNS[2:]

FRED_SERIES_COLUMNS: Final[list[str]] = [
    SERIES_ID,
    LABEL_DATE,
    FEATURE_VALUE,
]
FRED_SERIES_KEY: Final[list[str]] = [SERIES_ID, LABEL_DATE]
FRED_SERIES_ID_KEY: Final[list[str]] = [SERIES_ID_ID, LABEL_DATE]
